In [1]:
import pandas as pd

Applying a function to all the values in a column apply()

In [2]:
df=pd.DataFrame({
    "A":[2,3],
    "B":[4,5],
    "C":[6,7]
})
df

   A  B  C
0  2  4  6
1  3  5  7

Creating a new column D by adding existing columns B and C

In [3]:
def foo(row): 
    return row["B"] + row["C"] 
df["D"] = df.apply(foo, axis=1)
df

   A  B  C   D
0  2  4  6  10
1  3  5  7  12

Creating a new column D by multiplying 2 with column A

In [4]:
def foo(row): 
    return(row*2) 
df["D"] = df["A"].apply(foo)
df

   A  B  C  D
0  2  4  6  4
1  3  5  7  6

Apply and lambda

In [6]:
df["D"] = df.apply(lambda row: row["B"] + row["C"], axis=1)
df

   A  B  C   D
0  2  4  6  10
1  3  5  7  12

Creating a new column D by multiplying 2 with column A

In [7]:
df["D"] = df["A"].apply(lambda row: row*2)
df

   A  B  C  D
0  2  4  6  4
1  3  5  7  6

Pandas Reading different file sources

1. Reading a CSV File

In [9]:
# Reading a CSV file into a DataFrame in different styles 
#df=pd.read_csv('C:\\DataScience\\Workspace\\dataset\\data.csv') 
#df=pd.read_csv('C:/DataScience/Workspace/dataset/data.csv') 
#df = pd.read_csv(r'C:\DataScience\Workspace\dataset\data.csv') 
# if current location is #'F:\DataScience\Workspace\ 
#df = pd.read_csv('dataset\data.csv') or 
#df = pd.read_csv('dataset/data.csv') 

#if current location is dataset ie same folder where data is located 
df = pd.read_csv('Superstore.csv', encoding='cp437')

In [12]:
# Display the first few 5 of the DataFrame 
df.head()
# Display the first few 10 of the DataFrame 
#print(df.head(10))

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164